pipeline {
  agent any
  tools {
    maven 'Maven 3.9.9'
    jdk 'OpenJDK17'
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    skipStagesAfterUnstable()
    timestamps()
    disableConcurrentBuilds()
  }
  triggers {
    snapshotDependencies()
  }
  stages {
    stage('Setup') {
      steps {
        script {
          env.VERSION = """${sh(returnStdout: true, script: './build/get-version.sh ${RELEASE}')}"""
        }
      }
    }

    stage('Quick build') {
      tools {
        jdk 'OpenJDK17'
      }
      steps {
        withMaven () {
          sh 'mvn clean install -DskipTests'
        }
      }
    }
    stage('Build Spark Docker image') {
      steps {
        sh 'build/spark-docker-build.sh false ${VERSION}'
      }
    }
    stage('Build Standalone Spark Docker image') {
      steps {
        sh 'build/spark-docker-standalone-build.sh false ${VERSION}'
      }
    }
  }
}
