gbif.api.url=https://api.gbif.org/v1/
zookeeper.url=localhost
keygen.table.occ=keygen
keygen.table.counter=keygen_counter
keygen.table.lookup=keygen_lookup
taxonomy.tableName=taxonomy
geocode.tableName=geocode